-- RAG-Fin persistent storage used by the backend.
-- The API connects with the server-side database role; these tables are not
-- part of the browser-facing Data API contract.

begin;

create table if not exists public.ragfin_json_cache (
    cache_key text primary key,
    payload jsonb not null,
    updated_at timestamptz not null default now()
);

create index if not exists idx_ragfin_json_cache_updated_at
    on public.ragfin_json_cache (updated_at);

create table if not exists public.instruments (
    kind text not null,
    symbol text not null,
    name text,
    short_name text,
    source text,
    source_id text,
    logo_url text,
    logo_source text,
    active integer not null default 1,
    as_of text,
    metadata_json text not null default '{}',
    created_at text not null,
    updated_at text not null,
    primary key (kind, symbol)
);

create index if not exists idx_instruments_symbol
    on public.instruments (symbol);

create index if not exists idx_instruments_kind_active
    on public.instruments (kind, active);

create table if not exists public.instrument_aliases (
    alias text primary key,
    kind text not null,
    symbol text not null,
    source text,
    updated_at text not null
);

create index if not exists idx_instrument_aliases_target
    on public.instrument_aliases (kind, symbol);

create table if not exists public.fund_prices (
    fund_code text not null,
    date text not null,
    source text not null,
    price real not null check (price > 0),
    daily_return real,
    aum real,
    investor_count integer,
    share_count real,
    metadata_json text not null default '{}',
    raw_json text,
    fetched_at text not null,
    created_at text not null,
    updated_at text not null,
    primary key (fund_code, date, source)
);

create index if not exists idx_fund_prices_code_date
    on public.fund_prices (fund_code, date);

create index if not exists idx_fund_prices_code_date_updated
    on public.fund_prices (fund_code, date, updated_at desc);

create table if not exists public.fund_price_warnings (
    id bigint generated by default as identity primary key,
    fund_code text,
    date text,
    source text not null,
    warning text not null,
    metadata_json text not null default '{}',
    raw_json text,
    fetched_at text not null
);

create index if not exists idx_fund_price_warnings_code_date
    on public.fund_price_warnings (fund_code, date);

commit;
